from Locale import Locale

class RuleBasedCollator:
    ...
    def getSortKey(self, text: str) -> bytes: ...
    def compare(self, text: str, other: str) -> int: ...

def createInstance(locale: Locale) -> RuleBasedCollator: ...
