from datetime import datetime

import yaml
from create_songs_getter import create_playlist


def main():
    song_list: list[dict[str, str | datetime | list[str]]] = [
        {
            "title": song["title"],
            "artist": song["artist"],
            "album": song["album"],
            "genre": song["genre"],
            "date_added": song["date_added"],
        }
        for song in create_playlist()
    ]

    with open("songs.yaml", "w", encoding="utf-8") as f:
        f.write(f"# Generated by `catalog.py` on {datetime.now()}.\n")
        f.write(f"# Tracks count: {len(song_list)}.\n")
        f.write(yaml.dump(song_list, width=1000, allow_unicode=True, sort_keys=False))


main() if __name__ == "__main__" else None
